[tool.poetry]
name = "my-package"
version = "0.1.0"
description = "Super math package"

license = "MIT"

authors = [
    "zimch"
]

[tool.poetry.dependencies]
# просто так :)
python = ">=3.8"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.2"